### ISSUE TITLE
Replace Hard-coded Paths with Already Existing Variable

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/github-actions-for-desktop-apps#17]
## Problematic

At the end of the YAML for the continuous integration example, the **upload-artifact** step `path` uses a hard coded folder path:

https://github.com/microsoft/github-actions-for-desktop-apps/blob/d0fbf5cbc39057dea30244fb7ef6c5ae9c3b1ab8/.github/workflows/ci.yml#L93

## Recommended

I believe this should be using the `Wap_Project_Directory` variable plus "AppPackages" subfolder instead.

Snippet

```yml
# Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
- name: Upload build artifacts
  uses: actions/upload-artifact@v1
  with:
    name: MSIX Package
    path: '$env:Wap_Project_Directory\AppPackages\'
```

[Edit] - Added the subfolder name to the variable. I'm not sure that's how to concatenate the variable with a string in GitHub actions yet, but you get the point
